apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:10.1.0
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /etc/grafana/provisioning/datasources
          name: grafana-datasources
          readOnly: false
        - mountPath: /var/lib/grafana/dashboards
          name: grafana-dashboards
          readOnly: false
        - mountPath: /etc/grafana/provisioning/dashboards
          name: grafana-provisionning
          readOnly: false
        #- name: dashboard-volume
         # mountPath: /etc/grafana/provisioning/dashboards
        #- name: dashboard-data-volume
        #  mountPath: /var/lib/grafana/dashboards
        env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: "Admin"
        - name: GF_AUTH_DISABLE_LOGIN_FORM
          value: "true"
      volumes:
      - name: grafana-datasources
        configMap:
          defaultMode: 420
          name: grafana-datasources
      - name: grafana-dashboards
        configMap:
          defaultMode: 420
          name: dashboards
      - name: grafana-provisionning
        configMap:
          defaultMode: 420
          name: grafana-provisionning
    #  - name: dashboard-volume
    #    hostPath:
    #     path: D:\SarraDesktop\PFE\k8s\docker\grafana\provisioning
    #  - name: dashboard-data-volume
    #    hostPath:
    #      path: D:\SarraDesktop\PFE\k8s\docker\grafana\dashboards
--- #multiple yaml configuration within 1 file

apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000 #l service accessible fel cluster bl @ip te3ou w bl port tajjm t7otnfs l port maa l container kima tajjm lee
      targetPort: 3000 #container port ya3ni l port mta3 l pods that belongs to the service
      nodePort: 30104
