apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: default
data: #l format li jey mch kif docker compose 
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access": "proxy",
                "editable": false,
                "name": "Prometheus",
                "type": "prometheus",
                "url": "http://prometheus-service:9090", 
                "jsonData": {
                    "httpMethod": "POST",
                    "exemplarTraceIdDestinations": [
                        {
                            "name": "trace_id",
                            "datasourceUid": "tempo"
                        }
                    ]
                }
            },
            {
                "access": "proxy",
                "editable": false,
                "name": "Tempo",
                "type": "tempo",
                "orgId": 1,
                "url": "http://tempo-service:3200",
                "basicAuth": false,
                "isDefault": true,
                "version": 1,
                "uid": "tempo",
                "jsonData": {
                    "httpMethod": "GET",
                    "tracesToLogs": {
                        "datasourceUid": "loki"
                    },
                    "nodeGraph": {
                        "enabled": true
                    }
                }
            },
            {
                "access": "proxy",
                "editable": false,
                "name": "Loki",
                "type": "loki",
                "uid": "loki",
                "orgId": 1,
                "url": "http://loki-service:3100",
                "basicAuth": false,
                "isDefault": false,
                "version": 1,
                "jsonData": {
                    "derivedFields": [
                        {
                            "datasourceUid": "tempo",
                            "matcherRegex": "\\[.+,(.+?),",
                            "name": "TraceID",
                            "url": "${__value.raw}"
                        }
                    ]
                }
            }
        ]
    }
  