#msa with external service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msa-deployment
  labels:
    app: msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa
  template:
    metadata:
      labels:
        app: msa
    spec:
      containers:
      - name: msa
        image: tasneemgh/microview_a:2
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user 
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: postgres-url
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092

--- #multiple yaml configuration within 1 file

apiVersion: v1
kind: Service
metadata:
  name: msa-service
spec:
  type: NodePort
  selector:
    app: msa
  ports:
    - protocol: TCP
      port: 8080 #l service accessible fel cluster bl @ip te3ou w bl port tajjm t7otnfs l port maa l container kima tajjm lee
      targetPort: 8080 #container port ya3ni l port mta3 l pods that belongs to the service
      nodePort: 30100
      name: main
    - protocol: TCP
      port: 9090 #l service accessible fel cluster bl @ip te3ou w bl port tajjm t7otnfs l port maa l container kima tajjm lee
      targetPort: 9090 #container port ya3ni l port mta3 l pods that belongs to the service
      name: prom