apiVersion: apps/v1
kind: Deployment
metadata:
  name: msb-deployment
  labels:
    app: msb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msb
  template:
    metadata:
      labels:
        app: msb
    spec:
      containers:
      - name: msb
        image: tasneemgh/microview_b:2
        ports:
        - containerPort: 8081
        env:
        - name: SERVICEA_URL
          value: msa-service:8080 
        - name: SERVER_PORT
          value: "8081"
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: kafka-service:9092

--- #multiple yaml configuration within 1 file

apiVersion: v1
kind: Service
metadata:
  name: msb-service
spec:
  type: NodePort
  selector:
    app: msb
  ports:
    - protocol: TCP
      port: 8081 #l service accessible fel cluster bl @ip te3ou w bl port tajjm t7otnfs l port maa l container kima tajjm lee
      targetPort: 8081 #container port ya3ni l port mta3 l pods that belongs to the service
      nodePort: 30101
      name: main
    - protocol: TCP
      port: 9090 
      targetPort: 9090 #lkl faza mtaa \metrics
      name: prom
