apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 2s
      evaluation_interval: 2s

    scrape_configs:
    
      - job_name: 'MicroserviceA'
        static_configs:
          - targets: ['msa-service:9090'] 

      - job_name: 'MicroserviceB'
        static_configs:
          - targets: ['msb-service:9090'] 

      - job_name: 'MicroserviceC'
        static_configs:
          - targets: ['msc-service:9090']