apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
data:
  tempo.yaml: |-
    server:
      http_listen_port: 3200

    distributor:
      receivers:
        zipkin:
        otlp:
          protocols: 
            grpc:

    storage:
      trace:
        backend: local
        local:
          path: /tmp
